branch-defaults:
  master:
    environment: rag-openai-env3
    group_suffix: null
global:
  application_name: rag-openai-starter
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
